# CodeRabbit Configuration
# https://docs.coderabbit.ai/reference/configuration
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

reviews:
  # ============================================
  # Review Profile
  # ============================================
  # "assertive" - Thorough, detailed feedback (recommended for pedantic enforcement)
  # "chill" - Relaxed, fewer nitpicks
  profile: "assertive"

  # ============================================
  # Approval Workflow
  # ============================================
  # When true: Submit "Request Changes" when actionable comments exist
  # When all comments are resolved: Submit "Approved"
  # This integrates with branch protection rules requiring approvals
  request_changes_workflow: true

  # ============================================
  # Review Output
  # ============================================
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  # ============================================
  # Auto Review
  # ============================================
  auto_review:
    enabled: true
    drafts: false
    # Only review changed code on subsequent pushes (faster reviews)
    auto_incremental_review: true

  # Stop review if PR is closed/merged
  abort_on_close: true

  # ============================================
  # Path-Specific Instructions
  # ============================================
  path_instructions:
    - path: "**/*.py"
      instructions: |
        - Enforce type hints on all function signatures
        - Check for proper exception handling (no bare except)
        - Verify docstrings on public functions/classes
    - path: "**/*.sh"
      instructions: |
        - Verify scripts use set -euo pipefail
        - Check for proper quoting of variables
        - Ensure portable syntax (POSIX where possible)
    - path: "**/tests/**"
      instructions: |
        - Focus on test coverage and edge cases
        - Verify meaningful assertions (not just checking for no errors)
        - Check for test isolation (no shared state)
    - path: "**/*.md"
      instructions: |
        - Check for spelling and grammar
        - Verify links are valid
        - Ensure consistent formatting

  # ============================================
  # Static Analysis Tools
  # ============================================
  tools:
    ruff:
      enabled: true
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    languagetool:
      enabled: true

  # ============================================
  # Finishing Touches (AI-generated additions)
  # ============================================
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

# ============================================
# Chat
# ============================================
chat:
  auto_reply: true

