"""Pre-commit configuration assembly."""

from __future__ import annotations

import sys
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from pathlib import Path

    from codeagent.init.detector import LanguageRegistry


class MultilineDumper(yaml.SafeDumper):
    """Custom YAML dumper that uses block style for multiline strings."""


def _str_representer(dumper: MultilineDumper, data: str) -> yaml.Node:
    """Represent multiline strings with block style."""
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


MultilineDumper.add_representer(str, _str_representer)


def load_template(template_path: Path) -> dict[str, Any]:
    """Load a pre-commit template YAML file.

    Args:
        template_path: Path to template file

    Returns:
        Parsed YAML dictionary

    Raises:
        FileNotFoundError: If template doesn't exist
        yaml.YAMLError: If template is invalid YAML
        TypeError: If template is not a dict

    """
    with template_path.open() as f:
        result = yaml.safe_load(f)
    if not isinstance(result, dict):
        msg = f"Template must be a dict, got {type(result).__name__}"
        raise TypeError(msg)
    return result


def assemble_config(
    languages: list[str],
    registry: LanguageRegistry,
    templates_dir: Path,
) -> dict[str, Any]:
    """Merge base + detected language templates.

    Args:
        languages: List of detected language keys
        registry: Language registry
        templates_dir: Path to templates/pre-commit/ directory

    Returns:
        Merged pre-commit configuration dictionary

    """
    # Always start with base template
    base_path = templates_dir / "base.yaml"
    config = load_template(base_path)
    config.setdefault("repos", [])

    # Merge each detected language's template
    for lang in languages:
        lang_config = registry.get(lang, {})
        template_name = lang_config.get("pre_commit_template")

        if not template_name:
            continue

        template_path = templates_dir / template_name
        if not template_path.exists():
            sys.stderr.write(
                f"Warning: Template {template_name} not found\n",
            )
            continue

        lang_template = load_template(template_path)
        repos = lang_template.get("repos")
        if isinstance(repos, list):
            config["repos"].extend(repos)

    return config


def write_config(config: dict[str, Any], output_path: Path) -> None:
    """Write assembled config to file with header.

    Args:
        config: Assembled pre-commit configuration
        output_path: Path to write .pre-commit-config.yaml

    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        ruler = "# " + "=" * 75 + "\n"
        f.write(ruler)
        f.write("# CodeAgent - Auto-Generated Pre-Commit Configuration\n")
        f.write(ruler)
        f.write("# Generated by: codeagent init\n")
        f.write("# Do not edit manually - regenerate with:\n")
        f.write("#   codeagent init --force\n")
        f.write(ruler + "\n")
        yaml.dump(
            config,
            f,
            Dumper=MultilineDumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
